# Generated by Django 3.2 on 2023-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_img'),
        ),
    ]
